#!/usr/bin/env node
// Reads design-system/tokens/shared.json + tokens/<variant>.json (classic.json for "a",
// varm.json for "b") and emits src/app/theme-tokens.generated.css: a set of CSS custom
// properties under :root, prefixed --tst- (Tur Second Hand Tokens). This is the single
// source of truth also consumed by the WordPress theme.json overrides — no color/spacing
// value should ever be hand-copied into this repo a second time.
//
// Runs automatically before `next dev` and `next build` (see package.json "predev"/
// "prebuild"). Re-run manually with `npm run generate-theme` after editing token JSON.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// react/app/scripts -> react/app -> react -> <project root>
const projectRoot = resolve(__dirname, "../../..");

const variant = (process.env.NEXT_PUBLIC_THEME_VARIANT || "a").toLowerCase();
const variantFile = variant === "b" ? "varm.json" : "classic.json";

const tokensDir = process.env.DESIGN_TOKENS_DIR || resolve(projectRoot, "design-system/tokens");

function readTokens(filename) {
  const path = resolve(tokensDir, filename);
  return JSON.parse(readFileSync(path, "utf-8"));
}

const shared = readTokens("shared.json");
const variantTokens = readTokens(variantFile);
const tokens = { ...shared, ...variantTokens };

// camelCase -> kebab-case (e.g. colorPrimaryDark -> color-primary-dark, space4 -> space-4,
// text2xl -> text-2xl)
function toKebab(key) {
  return key
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/([a-zA-Z])([0-9])/g, "$1-$2")
    .toLowerCase();
}

const lines = Object.entries(tokens).map(([key, value]) => `  --tst-${toKebab(key)}: ${value};`);

const css = `/* AUTO-GENERATED by scripts/generate-theme.mjs — do not edit by hand.
 * Source: design-system/tokens/shared.json + design-system/tokens/${variantFile}
 * Variant: ${variant} (NEXT_PUBLIC_THEME_VARIANT=${variant})
 * Regenerate with: npm run generate-theme
 */
:root {
${lines.join("\n")}
}
`;

const outDir = resolve(__dirname, "../src/app");
mkdirSync(outDir, { recursive: true });
const outPath = resolve(outDir, "theme-tokens.generated.css");
writeFileSync(outPath, css, "utf-8");

console.log(`Generated ${outPath} from variant "${variant}" (${variantFile}).`);
